name: 'Get SMS list'
description: 'Reach out to Twilio to fetch a list of SMS/Messages'
inputs:
  phone:
    description: 'Phone number to search'
    required: true
    default: ''
  text:
    description: 'Text to search in the body of the message'
    required: true
    default: ''
  retries:
    description: 'How many times should the Twilio API get call to check for new messages'
    required: true
    default: '1'
outputs:
  found:
    description: 'Returns true if the text was found in the body of on one of the messages received by the provided number'
runs:
  using: 'node12'
  main: 'dist/index.js'
